version: "3.7"
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    env_file: ../.env
    environment:
      - API_KEY=$CF_DDNS_API_KEY
      - ZONE=$CF_DDNS_DOMAIN
      - SUBDOMAIN=$CF_DDNS_SUBDOMAIN
      - PROXIED=false
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    env_file: ../.env
    environment:
      - PEERS=$VPN_PEERS
      - SERVERURL=$VPN_SERVERURL
    volumes:
      - $DATA_DIR/wireguard:/config
      - /lib/modules:/lib/modules
    networks:
      - proxy
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
networks:
  proxy:
    name: proxy
    external: true
  default:
    driver: bridge
