version: "3.7"
services:
  homeassistant:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    env_file: ../.env
    ports:
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATA_DIR/homeassistant:/config
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.homeassistant.rule=Host(`homeassistant.$DOMAIN_NAME`)'
      - 'traefik.http.routers.homeassistant.entrypoints=web'
      ## HTTP Services
      - 'traefik.http.routers.homeassistant.service=homeassistant-svc'
      - 'traefik.http.services.homeassistant-svc.loadbalancer.server.port=8123'
networks:
  proxy:
    name: proxy
    external: true
  default:
    driver: bridge