version: "3.7"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    env_file: ../.env
    environment:
      - USER=$BT_USER
      - PASS=$BT_PASS
    volumes:
      - $DATA_DIR/transmission:/config
      - /storage:/storage
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.transmission.rule=Host(`transmission.$DOMAIN_NAME`)'
      - 'traefik.http.routers.transmission.entrypoints=web'
      ## HTTP Services
      - 'traefik.http.routers.transmission.service=transmission-svc'
      - 'traefik.http.services.transmission-svc.loadbalancer.server.port=9091'
    networks:
      - proxy
    restart: unless-stopped
  flood:
    image: jesec/flood
    container_name: flood
    env_file: ../.env
    environment:
      - HOME=$FLOOD_HOME
    user: $PUID:$PGID
    command:
      - --rundir=/config
      - --allowedpath /storage
      - --baseuri=/flood
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - $DATA_DIR/flood:/config
      - /storage:/storage:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - "traefik.http.routers.flood.entrypoints=web"
      # - "traefik.http.routers.flood.rule=Host(`$APPS_DOMAIN`) && PathPrefix(`/flood`)"
      - 'traefik.http.routers.flood.rule=Host(`flood.$DOMAIN_NAME`) && PathPrefix(`/flood`)'
      ## HTTP Services
      - "traefik.http.routers.flood.service=flood-svc"
      - "traefik.http.services.flood-svc.loadbalancer.server.port=3000"
    networks:
      - proxy
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    env_file: ../.env
    environment:
      - AUTO_UPDATE=true
    volumes:
      - $DATA_DIR/jackett:/config
      - /storage:/storage
    ports:
      - 9117:9117
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      - transmission
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jackett.entrypoints=web"
      # - "traefik.http.routers.jackett.rule=Host(`$APPS_DOMAIN`) && PathPrefix(`/jackett`)"
      - "traefik.http.routers.jackett.rule=Host(`jackett.$DOMAIN_NAME`)"
      - "traefik.http.routers.jackett.priority=99"
      ## HTTP Services
      - "traefik.http.routers.jackett.service=jackett-svc"
      - "traefik.http.services.jackett-svc.loadbalancer.server.port=9117"
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    env_file: ../.env
    depends_on:
      - transmission
      - jackett
    volumes:
      - $DATA_DIR/radarr:/config
      - /storage:/storage
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.radarr.entrypoints=web"
      # - "traefik.http.routers.radarr.rule=Host(`$APPS_DOMAIN`) && PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.rule=Host(`radarr.$DOMAIN_NAME`)"
      ## HTTP Services
      - "traefik.http.routers.radarr.service=radarr-svc"
      - "traefik.http.services.radarr-svc.loadbalancer.server.port=7878"
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    env_file: ../.env
    depends_on:
      - transmission
      - jackett
    volumes:
      - $DATA_DIR/sonarr:/config
      - /storage:/storage
    ports:
      - 8989:8989
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.sonarr.entrypoints=web"
      # - "traefik.http.routers.sonarr.rule=Host(`$APPS_DOMAIN`) && PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.$DOMAIN_NAME`)"
      ## HTTP Services
      - "traefik.http.routers.sonarr.service=sonarr-svc"
      - "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"
    restart: unless-stopped
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    env_file: ../.env
    volumes:
      - $DATA_DIR/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - "traefik.http.routers.ombi.entrypoints=web"
      # - "traefik.http.routers.ombi.rule=Host(`$APPS_DOMAIN`) && PathPrefix(`/ombi`)"
      - 'traefik.http.routers.ombi.rule=Host(`ombi.$DOMAIN_NAME`)'
      ## HTTP Services
      - "traefik.http.routers.ombi.service=ombi-svc"
      - "traefik.http.services.ombi-svc.loadbalancer.server.port=3579"
    networks:
      - proxy
networks:
  proxy:
    name: proxy
    external: true
  default:
    driver: bridge